from fraime.exceptions import (
    FraimeAPIError,
    FraimeAuthError,
    FraimeConnectionError,
    FraimeError,
)
from fraime.main import FraimeClient
from fraime.model import (
    PROMPT_FIELDS_BY_VIDEO_TYPE,
    AspectRatio,
    CinematicPromptFields,
    GenerateVideoRequest,
    GenerateVideoResponse,
    GenerationParams,
    MotionGraphicsPromptFields,
    MusicVideoPromptFields,
    PresenterPromptFields,
    PromptFields,
    Reference,
    SocialAdPromptFields,
    UGCPromptFields,
    VideoType,
)

__all__ = [
    "FraimeClient",
    "VideoType",
    "PROMPT_FIELDS_BY_VIDEO_TYPE",
    "AspectRatio",
    "GenerationParams",
    "Reference",
    "PromptFields",
    "CinematicPromptFields",
    "UGCPromptFields",
    "PresenterPromptFields",
    "SocialAdPromptFields",
    "MusicVideoPromptFields",
    "MotionGraphicsPromptFields",
    "GenerateVideoRequest",
    "GenerateVideoResponse",
    "FraimeError",
    "FraimeConnectionError",
    "FraimeAuthError",
    "FraimeAPIError",
]
